import Head from "next/head";
import type { AppProps } from "next/app";
import Layout from "@/components/layout/layout";
import { CartProvider } from "@/hooks/useCart";
import { AlertProvider } from "@/hooks/useAlert";
import { AnimatePresence } from "framer-motion";

export default function App({ Component, pageProps, router }: AppProps) {
  return (
    <>
      <Head>
        <title>Clothify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <CartProvider>
        <AlertProvider>
          <Layout>
            <AnimatePresence mode={"wait"}>
              <Component key={router.pathname} {...pageProps} />
            </AnimatePresence>
          </Layout>
        </AlertProvider>
      </CartProvider>
    </>
  );
}
